CREATE TABLE cache_rule (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path_pattern VARCHAR(512)             NOT NULL,
    methods      VARCHAR(128)             NOT NULL DEFAULT 'GET',
    ttl_seconds  BIGINT                   NOT NULL,
    max_size     BIGINT                   NOT NULL DEFAULT 10000,
    enabled      BOOLEAN                  NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_cache_rule_enabled ON cache_rule (enabled);
