CREATE TABLE application (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug                VARCHAR(64)              NOT NULL UNIQUE,
    name                VARCHAR(128)             NOT NULL,
    base_url            VARCHAR(512)             NOT NULL,
    description         VARCHAR(512),
    default_ttl_seconds BIGINT,
    enabled             BOOLEAN                  NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at          TIMESTAMP WITH TIME ZONE
);

CREATE INDEX idx_application_slug ON application (slug);

-- cache_rule now targets an application and gains ops fields.
-- application_id is nullable at the DB level for migration safety (no prod data);
-- it is required at the API layer and rules without an app are ignored by the registry.
ALTER TABLE cache_rule ADD COLUMN application_id BIGINT;
ALTER TABLE cache_rule ADD COLUMN description    VARCHAR(512);
ALTER TABLE cache_rule ADD COLUMN updated_at     TIMESTAMP WITH TIME ZONE;

-- ttl_seconds becomes optional; effective TTL falls back to application.default_ttl_seconds.
ALTER TABLE cache_rule ALTER COLUMN ttl_seconds DROP NOT NULL;

ALTER TABLE cache_rule
    ADD CONSTRAINT fk_cache_rule_application
    FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE CASCADE;

CREATE INDEX idx_cache_rule_application ON cache_rule (application_id);
